name: "fluent-prod"
services:
  redis:
    image: redis:latest
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis-data:/data
    ports:
      - "7200:6379"
    networks:
      - fluent-prod-net

  api-entrypoint-pg:
    image: postgres:18
    restart: always
    env_file:
      - ./prod.env
    environment:
      POSTGRES_USER: ${API_ENTRYPOINT_DB_USER}
      POSTGRES_PASSWORD: ${API_ENTRYPOINT_DB_PASSWORD}
    volumes:
      - api-entrypoint-pg-data:/var/lib/postgresql
    ports:
      - "7100:5432"
    networks:
      - fluent-prod-net

  users-service-pg:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${USERS_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USERS_SERVICE_DB_PASSWORD}
    volumes:
      - users-service-pg-data:/var/lib/postgresql
    ports:
      - "7102:5432"
    networks:
      - fluent-dev-net

  api-entrypoint:
    image: scobca/fluent-api-entrypoint:latest
    restart: always
    environment:
      API_ENTRYPOINT_DOPPLER_ACCESS_KEY: ${API_ENTRYPOINT_DOPPLER_ACCESS_KEY}
    volumes:
      - api-entrypoint-data:/var
    ports:
      - "7000:8080"
    networks:
      - fluent-prod-net

  users-service:
    image: scobca/fluent-users-service:latest
    restart: always
    environment:
      USERS_SERVICE_DOPPLER_ACCESS_KEY: ${USERS_SERVICE_DOPPLER_ACCESS_KEY}
    volumes:
      - users-service-data:/var/
    ports:
      - "7002:8082"
    networks:
      - fluent-dev-net

volumes:
  redis-data:
  api-entrypoint-pg-data:
  users-service-pg-data:
  api-entrypoint-data:
  users-service-data:

networks:
  fluent-prod-net:
    driver: bridge
