package org.fluent.enums

enum class MicroserviceName {
    API_ENTRYPOINT,
    AUTH_SERVICE,
    GRADE_SYNK_SERVICE,
    NOTIFICATION_SERVICE,
    QUEUE_SERVICE,
    SPREADSHEET_CONNECTOR_SERVICE,
    USER_SERVICE,
}